// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcwgtxvzbmodybodtzxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtjd2d0eHZ6Ym1vZHlib2R0enhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNzQxNTksImV4cCI6MjA2Mjk1MDE1OX0.kNL_aAZrTPs2WixuHLNBe4IoclcRAOr582mXpbLXfIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);